format = """\
[](fg:#223249)\
[](fg:#223249 bg:#54546D)\
$time\
[](fg:#54546D bg:#658594)\
$directory\
[](fg:#658594 bg:#E6C384)\
$git_branch\
$git_metrics\
[](fg:#E6C384)\
$character\
"""

[directory]
format = "[ $path ]($style)"
style = "fg:#16161D bg:#658594"

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
style = "fg:#16161D bg:#E6C384"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#16161D bg:#E6C384"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = "  "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white"

[character]
success_symbol = ' ➜ '
error_symbol = ' ✗ '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#54546D fg:#16161D"
format = '[ $time ]($style)'
